/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vetcontrol.Views;

import com.mycompany.vetcontrol.DAO.ClienteDAO;
import com.mycompany.vetcontrol.DAO.MascotaDAO;
import com.mycompany.vetcontrol.Modelo.ClienteModel;
import com.mycompany.vetcontrol.Modelo.MascotaModel;
import java.awt.Component;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andy-
 */
public class FrmMascotas extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMascotas.class.getName());
     private final MascotaDAO dao = new MascotaDAO();
   
    
    private String[] columnas = {"idMascota", "nombre", "especie", "raza", "edad", "IdCliente"};

    /**
     * Creates new form FrmMascotas
     */
    public FrmMascotas() {
        initComponents();
 
         DefaultTableModel model = new DefaultTableModel (columnas, 0);
         TblMascotas.setModel(model);// Limpia los ítems por defecto del diseño
        
         
         //Configuramos el renderizador visual para que muestre el nombre del cliente dueño
         cmbIdCliente.setRenderer(new DefaultListCellRenderer() {
             @Override
             public Component getListCellRendererComponent(JList<?> list, Object value, 
                     int index, boolean isSelected, boolean cellHasFocus) {
                 super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                 // Evaluamos si el objeto dentro de la celda es de tu clase clienteModel
                 if (value instanceof ClienteModel) {
                     ClienteModel cliente = (ClienteModel) value;
                     setText(cliente.getNombre()); 
                 }
                 return this;
             }
         });
         
         cargarClientesCombo();
    }

    
    private void cargarClientesCombo(){
        
        try {
            // Declaramos el objeto DAO y el modelo por defecto del combobox
            ClienteDAO dao = new ClienteDAO();
            
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            // Pedimos que nos retorne la lista de clientes y metemos los objetos completos al modelo
            for (ClienteModel c : dao.listar()) {
                modeloCombo.addElement(c); 
            }
            cmbIdCliente.setModel(modeloCombo);
        
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los clientes dueños: " + ex.getMessage());
        }
          cargarMascotasTabla();
        
    }
    
        
    private void cargarMascotasTabla(){
         try {
        List<MascotaModel> lista = dao.listar(); 
        
         DefaultTableModel modeloMascota = (DefaultTableModel) TblMascotas.getModel();
        modeloMascota.setRowCount(0); 
       
        for (MascotaModel m : lista) {
            Object[] rowData = {      
                m.getIdMascota(),   
                m.getNombre(),      
                m.getEspecie(),   
                m.getRaza(),    
                m.getEdad(),  
                m.getIdCliente(),
            };
            modeloMascota.addRow(rowData);
        }
         TblMascotas.setModel(modeloMascota);
             
             // anchos de la tabla
             TblMascotas.getColumnModel().getColumn(0).setPreferredWidth(50);
             TblMascotas.getColumnModel().getColumn(1).setPreferredWidth(80);
             TblMascotas.getColumnModel().getColumn(2).setPreferredWidth(80);
             TblMascotas.getColumnModel().getColumn(3).setPreferredWidth(80);
             TblMascotas.getColumnModel().getColumn(4).setPreferredWidth(80);
             TblMascotas.getColumnModel().getColumn(5).setPreferredWidth(80);
        
         
         } catch (SQLException ex) {
             System.getLogger(FrmCliente.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
         }
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jpCeleste = new javax.swing.JPanel();
        lblMascota = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtRaza = new javax.swing.JTextField();
        lblRaza = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        lblEdad = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblMascotas = new javax.swing.JTable();
        txtEspecie = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        cmbIdCliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCeleste.setBackground(java.awt.SystemColor.activeCaption);

        lblMascota.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMascota.setForeground(new java.awt.Color(0, 0, 0));
        lblMascota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMascota.setText("Mascota");

        lblEspecie.setForeground(new java.awt.Color(0, 0, 0));
        lblEspecie.setText("Especie:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblNombre.setText("Nombre:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        lblRaza.setForeground(new java.awt.Color(0, 0, 0));
        lblRaza.setText("Raza");

        btnEliminar.setBackground(new java.awt.Color(255, 102, 102));
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        lblEdad.setForeground(new java.awt.Color(0, 0, 0));
        lblEdad.setText("Edad:");

        lblCliente.setForeground(new java.awt.Color(0, 0, 0));
        lblCliente.setText("IdCliente");

        TblMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "idMascota", "Nombre", "Edad", "raza", "Especie", "Dueño"
            }
        ));
        jScrollPane1.setViewportView(TblMascotas);

        cmbIdCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jpCelesteLayout = new javax.swing.GroupLayout(jpCeleste);
        jpCeleste.setLayout(jpCelesteLayout);
        jpCelesteLayout.setHorizontalGroup(
            jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCelesteLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(lblMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpCelesteLayout.createSequentialGroup()
                .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCelesteLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCelesteLayout.createSequentialGroup()
                                .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbIdCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jpCelesteLayout.createSequentialGroup()
                                .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCelesteLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCelesteLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(btnRegistrar)))
                        .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCelesteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(txtEspecie)))
                            .addGroup(jpCelesteLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btnRegresar)
                                .addGap(42, 42, 42)
                                .addComponent(btnEliminar))))
                    .addGroup(jpCelesteLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jpCelesteLayout.setVerticalGroup(
            jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCelesteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCelesteLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEspecie)
                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpCelesteLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdad)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRaza)
                            .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jpCelesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(btnRegistrar)
                    .addComponent(btnRegresar)
                    .addComponent(btnEliminar)
                    .addComponent(cmbIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCeleste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCeleste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
         try {
        //leer datos del formulario
        String nombre= txtNombre.getText().trim();
        String especie = txtEspecie.getText().trim();
        String raza = txtRaza.getText().trim();
        String edadStr = txtEdad.getText().trim();
        
        Object seleccionado = cmbIdCliente.getSelectedItem();
        
        // Validar
        if(nombre.isBlank()){
            JOptionPane.showMessageDialog(this,"El nombre de la mascota es obligatorio");
            return;
        }
        if(especie.isBlank()){
            JOptionPane.showMessageDialog(this,"La especie de la mascota es obligatoria");
            return;
        }
        if(raza.isBlank()){
            JOptionPane.showMessageDialog(this,"La raza de la mascota es obligatoria");
            return;
        }
        if(edadStr.isBlank()){
            JOptionPane.showMessageDialog(this,"La edad es obligatorio");
            return;
        }
        if(seleccionado == null){
            JOptionPane.showMessageDialog(this,"Debe seleccionar un cliente de la lista");
            return;
             
        }
        int edad = Integer.parseInt(edadStr);
        //convertimos el objeto generico del combo directamente a ClienteModel
        ClienteModel cliente = (ClienteModel) seleccionado;
        
        //modelo de mascota asignándole el ID del cliente 
        
        MascotaModel mascota = new MascotaModel(); 
        mascota.setNombre(nombre); 
        mascota.setEspecie(especie); 
        mascota.setRaza(raza); 
        mascota.setEdad(edad); 
        mascota.setIdCliente(cliente.getIdCliente()); //extraemos el id del cliente
             try {
                 dao.insertar(mascota);
             } catch (SQLException ex) {
                 System.getLogger(FrmMascotas.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
             }
        
        JOptionPane.showMessageDialog(this,"Registrado con éxito");
         cargarMascotasTabla(); 

       //limpiar los 
        txtNombre.setText("");
        txtEspecie.setText("");
        txtRaza.setText("");
        txtEdad.setText("");
  
        
       }catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "La edad debe ser un número entero","Error de Formato",JOptionPane.ERROR_MESSAGE);
       }
    

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        try{
            int filaSeleccionada = TblMascotas.getSelectedRow();
            
            // Validar si no seleccionó nada
            if (filaSeleccionada == -1) {
                JOptionPane.showMessageDialog(this, "Por favor, seleccione una mascota de la tabla.");
                return;
            }
            
             //Leemos el número de la columna 0 directamente de la pantalla
            int idMascotaReal = (int) TblMascotas.getValueAt(filaSeleccionada, 0);
            
             // Mandamos a llamar a  DAO
            dao.eliminar(idMascotaReal);
            JOptionPane.showMessageDialog(this, "¡Mascota eliminada correctamente!");
            
            cargarMascotasTabla();
            
        }catch (java.sql.SQLException ex){
            JOptionPane.showMessageDialog(this, "No se puede eliminar porque la mascota está asignada a una cita.");
        
        } catch (Exception ex){
            
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmMenu frmMenu =new FrmMenu();
        frmMenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMascotas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblMascotas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbIdCliente;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpCeleste;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
